### PR TITLE
Mr register

### PR DESCRIPTION
**Pull request by spuuun**
working registration component

### CODE REVIEW

**Comment by spuuun** [comment]
oh boy, i hope i get lotsa 👍 's

**Comment by spuuun** [comment]
hey team -- u guys heart my branch?

**Comment by spuuun** [comment]
team?

**Comment by mjimeneztn** [comment]
matt, destroy this NOW!!!!!!!!!!!!!!!
jk, looks great

**Comment by spuuun** [comment]
oh! 😨

**Comment by KevinSadler** [comment]
Hey it looks great, feel free to merge. -Hermit

**Comment by cbarr123** [comment]
👍

**Pull request merged**
